### ISSUE TITLE
OAuth 1.0 service at CILogon

### ISSUE THREAD

**Issue by taojing2002** [DataONEorg/d1_portal_servlet#1]
OAuth 1.0 endpoint is retiring this year on CILogon and all CILogon clients need  to migrate to OAuth 2.0 (OpenID Connect) as documented at https://www.cilogon.org/oidc.

**Comment by taojing2002** [comment]
In cn-sandbox environment, we will test the consequence if the  endpoint doesn't work. The approach will look like:
Modify the CILogon urs on /var/lib/tomcat8/webapps/portal/WEB-INF/client.xml file to make them invalid:
```
<serviceUri>https://cilogon.org/oauth</serviceUri>
<authorizeUri>https://cilogon.org/delegate</authorizeUri>
```
The new configuration will look like:
```
<serviceUri>https://cilogon.org/oauth-fake</serviceUri>
<authorizeUri>https://cilogon.org/delegate-fake</authorizeUri>
```
The testing will focus on the communication of cn and mns:

- Harvest
- Replication

**Comment by taojing2002** [comment]
I tested harvest and replications after enable those fake urls and got those objects successfully:
https://cn-sandbox.test.dataone.org/cn/v2/meta/testReplicate.1632436017422
https://cn-sandbox.test.dataone.org/cn/v2/meta/testReplicateData.1632436027648
https://cn-sandbox.test.dataone.org/cn/v2/meta/testReplicateJsonLD.1632436033954

I also could create a group successfully on search-sandbox.test.dataone.org after logged in by an ORCID.

I could use the cn certificate to delete an object (urn:uuid:efc3cab2-902f-4b1d-810e-5561fdd57396) on cn-sandbox.

I could use the mn certificate to delete an object (urn:uuid:efc3cab2-902f-4b1d-810e-5561fdd57396) on the member node.

I also used the mn certificate to force a synchronization.

**Comment by mbjones** [comment]
@taojing2002 that's great. Can you also test:

- user login via ORCID on MetacatUI works in that environment
    - I assume that logon via CILogon would no longer work, so we'd need to configure that off that to be off in MetacatUI, right?
- create(), update(), delete(), and archive() work on a MN with a JWT created via ORCID login in that environment

Anything else? Seems like there are more API ops like setting access control, etc. that could be tested, but if these work, seems like they all should.

If this all seems to work, then the next step I think would be to disable the CILogon URIs and logon UI in MetacatUI for all of our environments. @datadavev @laurenwalker @amoeba do you see any other issues we need to test for these auth changes?

**Comment by taojing2002** [comment]
I just talked with Dave and we thought DataONE wouldn't have any significant issues after CILogon disables the OAuth 1.0 service endpoint. 
The cn-sandbox environment is configured with that situation. Everyone can test it at your convenience.

**Comment by taojing2002** [comment]
Yeah. I tested to log in via ORCID on MetacatUI to create, update and publish packages. But I didn't test it by API calls through a token. I guess it should work. But I will do it.

**Comment by taojing2002** [comment]
I used curl commands to call those API methods with a JWT token and they worked on MN and the result also propagated to cn:

- create()
- update()
- archive()
- updateSystemmetadata()

**Comment by mbjones** [comment]
That's great. Any thoughts on the MetacatUI configuration to remove the CILogon authentication option? If that is a simple config change, then it can probably be done at the same time that you reconfigure the portal to point at fake CILogon services. 

Does anyone have objections or concerns with @taojing2002 proceeding with the removal of OAuth 1.0 support from the CN configuration, and reconfiguring all of our operational MetacatUI instances to no longer support CILogon as a login source?  cc: @datadavev @amoeba @laurenwalker @jeanetteclark @gothub @ThomasThelen

**Comment by taojing2002** [comment]
It is fine to me to remove the CILogon authentication option from MetacatUI. Do we even need to reconfigure the portal to point to fake CILogon service? I think if the OAuth 1.0 services are removed, the access will be thrown a not-found or some error page. It is equivalent to the fake urls.  What do you think?

**Comment by mbjones** [comment]
Well, we might want to add back in an OAuth 2 endpoint for CILogon eventually. So is removing it from the config better, or removing it overall? It woul dbe nice if we don't generate a bunch of spurious errors that we have to wade through in the logs as well.

**Comment by taojing2002** [comment]
For the MetacatUI part, I think it is better to remove it from config since we might bring it back when we support OAuth 2 for CIlogon.
For the server side, I think it is better to use fake urls just as we did on cn-sandbox. If we remove this whole part, I am worrying if the removing will cause NPEs:
```
<serviceUri>https://cilogon.org/oauth</serviceUri>
<authorizeUri>https://cilogon.org/delegate</authorizeUri>
``` 
If we don't provide the CIlogon interface on MetacatUI, i guess few people will use it log in.

**Comment by laurenwalker** [comment]
> That's great. Any thoughts on the MetacatUI configuration to remove the CILogon authentication option? If that is a simple config change, then it can probably be done at the same time that you reconfigure the portal to point at fake CILogon services.
> 
> Does anyone have objections or concerns with @taojing2002 proceeding with the removal of OAuth 1.0 support from the CN configuration, and reconfiguring all of our operational MetacatUI instances to no longer support CILogon as a login source? cc: @datadavev @amoeba @laurenwalker @jeanetteclark @gothub @ThomasThelen

Changing the  MetacatUI is a bit tricky but not a huge deal. The  main  [`signInUrl`](https://nceas.github.io/metacatui/docs/AppConfig.html#signInUrl) in the `AppConfig` is the CILogon endpoint, since that was the default auth provider when we first introduced the dataone portals. While the ORCID auth provider logon is [`signInUrlORCID`](https://nceas.github.io/metacatui/docs/AppConfig.html#signInUrlOrcid).  I think we'd want to eventually deprecate `signInUrlORCID` and change `signInUrl` to use the ORCID endpoint. I don't think many, if any, other repos using MetacatUI use CILogon. But I'll make sure that ORCID login doesn't break with these config changes.

We also have [enableCILogonSignIn](https://nceas.github.io/metacatui/docs/AppConfig.html#enableCILogonSignIn) which would need to be deprecated.

- I think we'll also  want to think about puttting in some help text on our sign in page in the DataONE theme for users looking for the CILogon button. 

- And we should think about how we want to  map identities between ORCIDs and CILogon subjects once users cannot do that  on their own via the UI.

**Comment by laurenwalker** [comment]
Oh, I just read  the  later comments about wanting to support  CILogon once  we support OAuth 2.0. In that case, I will justt  disable CILogon logins for now in  MetacatUI via `enableCILogonSignIn` and maybe replace it with  some help text.

**Comment by laurenwalker** [comment]
@mbjones  Today I am going to disable the CILogon button in the DataONE theme and replace the text under  the  button with a help message that CILogon is temporarily disabled and  if someone  needs an  identity  mapping, to  contact us. If you see any  issues with this  let me know.

![Screen Shot 2021-09-29 at 2 19 57 PM](https://user-images.githubusercontent.com/6643222/135327239-07661311-f9d5-4e89-8912-14aeaf63ae8c.png)

**Comment by laurenwalker** [comment]
New interface

![Screen Shot 2021-09-29 at 2 47 28 PM](https://user-images.githubusercontent.com/6643222/135330156-f85eefc7-2277-43f8-ae7a-1cf1e541592f.png)

**Comment by mbjones** [comment]
That sounds great! Given that we don't provide it for KNB or Arctic or ESS-DIVE anyways, I suspect there will be little impact.

**Comment by taojing2002** [comment]
So far no complains have reported.
